export const DIGITAL_MARCH_URL = 'https://ja.globalclimatestrike.net';
export const ORGANIZE_GOOGLE_FORM_URL = 'https://docs.google.com/forms/d/1Ru5in0Vbp23ciuVkt1Uv_EJG9LshArgF2MEJraoSAlw/viewform?edit_requested=true';
export const MUNICIPALITY_CED_LIST = 'https://www.es-inc.jp/ced/index.html';
export const ZERO_CARBON_CITY_LIST = 'https://www.env.go.jp/policy/zerocarbon.html';
export const DIGITAL_STRIKE_YOUTUBE = 'https://www.youtube.com/watch?v=xpYNJepgPmM&feature=emb_title'
export const FACEBOOK_SHARE_URL = 'https://www.facebook.com/share.php?u=https://fridaysforfuture.jp/';
export const YOUTUBE_CHANNEL_LINK = 'https://www.youtube.com/channel/UCmAxzODI33fBPXrXefFKgog';
export const VIDEO_A_URL = 'https://www.youtube.com/watch?v=TLdvpdU-rH0';
export const VIDEO_B_URL = 'https://www.youtube.com/watch?v=YUkruYxI5B4';
